### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by joseseb91**
first attempt

### CODE REVIEW

**Comment by joseseb91** [comment]
Testing

**Comment by joseseb91** [comment]
it came there

[Slack File: image.png](https://files.slack.com/files-pri/T033Q2E8HHR-F04LDQK5ZGX/image.png)

**Comment by joseseb91** [comment]
thread test

**Comment by joseseb91** [comment]
@sibin-impress approve and see

**Comment by joseseb91** [comment]
this is where ci/cd linting/testing updates come

[Slack File: image.png](https://files.slack.com/files-pri/T033Q2E8HHR-F04M70J8F25/image.png)

**Comment by joseseb91** [comment]
adding comment in github pr instead of slack

**Review by sibinms — APPROVED** [review]

**Comment by sibinms** [comment]
oh ethu shokam alle ?

**Comment by joseseb91** [comment]
auto archiving channel optional is there for paid, private channels possible in free. i can see why they made it per pr channel [](edited-with-Axolo)

**Pull request merged**
